import Head from 'next/head'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>

      </header>
      <main>
        <section className='banner'>

        </section>
        <section className='sections'>
          <section className='payments'></section>
          <section className='sales'></section>

          <section className='combo'>
            <h1>Hola, yo voy a trabajar acá</h1>
          </section>
          <section className='benefits'></section>
          <section className='discover'></section>
          <section className='stores'></section>
          
          <section className='super'></section>
          <section className='categories'></section>
        </section>
        <section className='pre-footer'>

        </section>
      </main>
      <footer>

      </footer>
    </>
  )
}