import Head from 'next/head'
import { Inter } from 'next/font/google'
import {Footer} from '@/components/Footer'
import { Prefooter } from '@/components/Prefooter'

const inter = Inter({ subsets: ['latin'] })

const indexPage=()=>{
  return (
    < >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>

      </header>
      <main >
        <section className='banner'>
        </section>
        <section className='sections'>
          <section className='payments'></section>
          <section className='sales'></section>
          <section className='combo'></section>
          <section className='benefits'></section>
          <section className='discover'></section>
          <section className='stores'></section>
          <section className='super'></section>
          <section className='categories'></section>
        </section>
          
      </main>
      <footer>
      <Prefooter/>
         <Footer/>
      </footer>
          
    </>
  )
}
export default indexPage;